### ISSUE TITLE
Failed to fetch preview 

### ISSUE THREAD

**Issue by kkor** [birkir/gatsby-source-prismic-graphql#4]
Hi again!

Finally got access to GraphQL in Prismic, but didn't get too far... 

With a super simple pages/index fetched based on the uid:

```
export const query = graphql`
    query {
        prismic {
            page(uid: "my-index", lang: "en-us") {
                title
            }
        }
    }
`;
```

I've setup the preview in url in prismic to "http://localhost:8000" & "/preview"

a )When I navigate to http://localhost:8000, I see the published title ("My index") and even the draft one ("My index (DRAFT EDIT)") in the preview thingie from prismic:

![image](https://user-images.githubusercontent.com/1140636/52213626-463c2e80-2898-11e9-9d1f-b27d2a32768b.png)

Is it supposed to show the page with preview content from the sidebar link? If so, it just reloads the same page when clicking the "draft preview".

b) When I navigate to the preview page from prismic's preview button, I can see it redirect to the preview/token=bla page correctly and then to http://localhost:8000, but there it throws:

![image](https://user-images.githubusercontent.com/1140636/52214017-586a9c80-2899-11e9-9623-2cdf6a41ed89.png)

"GraphQLError: Syntax Error: Unexpected Int "1826773283"
    at syntaxError (http://localhost:8000/commons.js:23614:10)
    at unexpected (http://localhost:8000/commons.js:28536:68)
    at parseDefinition (http://localhost:8000/commons.js:27210:9)
    at many (http://localhost:8000/commons.js:28566:16)
    at parseDocument (http://localhost:8000/commons.js:27170:18)
    at parse (http://localhost:8000/commons.js:27108:10)
    at parseDocument (http://localhost:8000/commons.js:23107:16)
    at gql (http://localhost:8000/commons.js:23148:10)
    at getQuery (http://localhost:8000/commons.js:21864:36)
    at getIsolatedQuery (http://localhost:8000/commons.js:21873:17)
    at _class2._callee$ (http://localhost:8000/commons.js:22677:81)
    at tryCatch (http://localhost:8000/commons.js:103443:40)
    at Generator.invoke [as _invoke] (http://localhost:8000/commons.js:103669:22)
    at Generator.prototype.(anonymous function) [as next] (http://localhost:8000/commons.js:103495:21)
    at asyncGeneratorStep (http://localhost:8000/commons.js:3694:24)
    at _next (http://localhost:8000/commons.js:3716:9)
    at http://localhost:8000/commons.js:3723:7
    at new Promise (<anonymous>)
    at _class2.<anonymous> (http://localhost:8000/commons.js:3712:12)
    at _class2.load (http://localhost:8000/commons.js:22714:25)
    at _class2.componentDidMount (http://localhost:8000/commons.js:22727:20)
    at _class2.componentDidMount (http://localhost:8000/commons.js:96247:123)
    at commitLifeCycles (http://localhost:8000/commons.js:84990:22)
    at commitAllLifeCycles (http://localhost:8000/commons.js:86355:7)
    at HTMLUnknownElement.callCallback (http://localhost:8000/commons.js:68912:14)
    at Object.invokeGuardedCallbackDev (http://localhost:8000/commons.js:68962:16)
    at invokeGuardedCallback (http://localhost:8000/commons.js:69019:31)
    at commitRoot (http://localhost:8000/commons.js:86551:7)
    at completeRoot (http://localhost:8000/commons.js:88003:3)
    at performWorkOnRoot (http://localhost:8000/commons.js:87932:9)
    at performWork (http://localhost:8000/commons.js:87840:7)
    at performSyncWork (http://localhost:8000/commons.js:87814:3)
    at requestWork (http://localhost:8000/commons.js:87683:5)
    at scheduleWork (http://localhost:8000/commons.js:87492:5)
    at scheduleRootUpdate (http://localhost:8000/commons.js:88160:3)
    at updateContainerAtExpirationTime (http://localhost:8000/commons.js:88188:10)
    at updateContainer (http://localhost:8000/commons.js:88245:10)
    at ReactRoot../node_modules/react-dom/cjs/react-dom.development.js.ReactRoot.render (http://localhost:8000/commons.js:88537:3)
    at http://localhost:8000/commons.js:88677:14
    at unbatchedUpdates (http://localhost:8000/commons.js:88043:10)
    at legacyRenderSubtreeIntoContainer (http://localhost:8000/commons.js:88673:5)
    at render (http://localhost:8000/commons.js:88734:12)
    at http://localhost:8000/commons.js:1039:7"

I didn't dig into it deeper yet, thought I'd ask first if I'm missing something obvious in my setup? If it's nothing obvious I can create a smaller reproduction and actually try to look into what's causing the error.

(I also tried setting the API to public, had no effect)

**Comment by birkir** [comment]
Looks like there is a malformed GraphQL query being sent.

Can you open the network tab and find the network request to graphql endpoint at prismic, copy the query and paste it here?

There is a "view source" link right next to "Request Payload" at the bottom, so it's easy to copy paste.

**Comment by kkor** [comment]
Woah, thanks for super fast reponses :D
There's a request to:
https://myrepo.prismic.io/previews/token/XFgwHxEAAOQ6vymn
where the token matches the preview cookie, but it's missing a payload if that's the one that should have it?
After that it keeps pinging:
https://myrepo.prismic.io/previews/XFgwHxEAAOQ6vymn/ping?ref=https%3A%2F%2Fmyrepo.prismic.io%2Fpreviews%2FXFhIpBEAAOQ6v49D
but no payloads there either?

**Comment by kkor** [comment]
Yeah, so if the query in `gatsby-browser` is supposed to be a graphql parsed from the component, then that's definitely failing now, it's just that int "1826773283":

![image](https://user-images.githubusercontent.com/1140636/52235091-d3e54180-28cb-11e9-865d-6c0f0e321536.png)

Looks like I'm doing something wrong, so I'll check out your example and try again.

**Comment by kkor** [comment]
Okay, issue found... and I should have thought of this earlier: I'm using typescript. Changing my index.tsx -> index.jsx fixed the preview issue.

SInce you're using typescript in the plugin, I'm hopeful there's typescript support hidden here somewhere? :)

**Comment by birkir** [comment]
Yes! Nice catch buddy! I'll update this issue tomorrow with a fix!

I am overwriting the babel loader that does not remove graphql queries (so they can be reused) and I remember a ts-plugin failed in some scenario. I'm on the phone now so let me research this a bit.

Thanks for the update!

**Comment by kkor** [comment]
Could also be difference in the tsconfig / imports? I can match yours if you provide it, i'm currently using:

```
{
    "compilerOptions": {
        "declaration": true,
        "emitDecoratorMetadata": true,
        "esModuleInterop": true,
        "experimentalDecorators": true,
        "forceConsistentCasingInFileNames": true,
        "noImplicitAny": true,
        "noUnusedLocals": true,
        "noUnusedParameters": true,
        "jsx": "react",
        "sourceMap": true,
        "strict": true,
        "target": "es5",
        "baseUrl": "./src",
        "module": "commonjs",
        "noImplicitReturns": true,
        "noImplicitThis": true,
        "preserveConstEnums": true,
        "removeComments": true,
        "strictNullChecks": true
    }
}
```

**Comment by birkir** [comment]
I've checked a project we have that uses typescript and don't see anything that is different, however maybe the order of plugins matter. Make sure to put this plugin after typescript plugin in gatsby-config.

```js
{
  "compilerOptions": {
    // Base directory to resolve non-relative module names.
    "baseUrl": "./src",
    // Specify module code generation
    "module": "commonjs",
    // Generates corresponding '.map' file.
    "sourceMap": true,
    // Enables experimental support for ES7 decorators.
    "experimentalDecorators": true,
    // Target latest version of ECMAScript.
    "target": "esnext",
    // Search under node_modules for non-relative imports.
    "moduleResolution": "node",
    // Process & infer types from .js files.
    "allowJs": true,
    // Don't emit; allow Babel to transform files.
    "noEmit": true,
    // Enable strictest settings like strictNullChecks & noImplicitAny.
    "strict": true,
    // Disallow features that require cross-file information for emit.
    "isolatedModules": true,
    // Import non-ES modules as default imports.
    "esModuleInterop": true,
    // Type declaration files to be included in compilation.
    "types": ["node"],
    // Specify library file to be included in the compilation.
    "lib": ["dom", "es2015", "es2017"],
    // Specify JSX code generation
    "jsx": "preserve",
    // Report errors on unused locals.
    "noUnusedLocals": true,
    // Report errors on unused parameters.
    "noUnusedParameters": true,
    // Do not emit comments to output.
    "removeComments": false,
    // Do not erase const enum declarations in generated code.
    "preserveConstEnums": true
  },
  // Specifies a list of glob patterns that match files to be included in compilation.
  "include": ["./src/**/*"]
}
```

**Comment by kkor** [comment]
Omg! That was it! Thanks a bunch, wouldn't have realised that on my own! 🎉 
Now let's hope everything else is smooth sailing :D

**Comment by birkir** [comment]
Glad to help. Don't hesitate to report any more issues you have
